import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.goto("http://localhost:5173", { waitUntil: "networkidle" });
await page.waitForTimeout(500);
await page.click("button:has-text('Dev:')");
await page.waitForTimeout(200);
await page.click("button:has-text('Admin')");
await page.waitForTimeout(500);
const navText = await page.textContent("nav");
console.log("Sidebar:", navText?.replace(/\s+/g, " ").trim());
await browser.close();
